" Break compatibility with VI
set nocompatible

" Enable syntax highlighting
syntax on
colorscheme ksw

" ~> File type detection
filetype on
filetype plugin on
filetype indent on

" ~> Prevent VIM from beeping 
set novisualbell
set noerrorbells

" ~> Tabs
set expandtab
set smarttab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" ~> Line numbers
set number
set relativenumber
