#!/bin/sh

# start redshift
if [ -f /usr/bin/redshift ]; then
  redshift -O 4000 &
fi

# start i3 and keep it running
if [ -f /usr/bin/i3 ]; then
  xrandr | grep 'HDMI-2 connected'
  hdmi=$?

  if [[ $hdmi -eq 0 ]] ; then
    xrandr --output HDMI-2 --mode 1920x1200 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-1 --off --output eDP-1 --off --output DP-2 --off
  else
    xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --off --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --off
  fi

  # Set a solid background for now
  xsetroot -solid "#458588"

  exec i3
fi
